""" a program that asks to enter number of users and asks for naming every user
and rolls dice as per chance"""
import random
while "Kalpak" != "Steven Jobs":
    print("_______________________________________________________")
    print("""
         """)
    print("-------------------------------------------------------------------------")
    print("""Note: max users can play are from 2 to 8.
                        y = yes , n = no
                        type n if you wnat to get other options""")
    print("-------------------------------------------------------------------------")
    pirates = raw_input("How many users are going to play:")
    print("-------------------------------------------------------------------------")
    if pirates =="n":
        feature_1 = "Other options are Start again or End:"
        if feature_1 == "Start again":
            continue
        elif feature_1 == "End":
            break
    elif pirates == "2":
        print("-------------------------------------------------------------------------")
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        while 2 == 2 :
            print("-------------------------------------------------------------------------")
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue    
    elif pirates == "3":
        print("-------------------------------------------------------------------------")
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------")
        while 2 == 2 :
            print("-------------------------------------------------------------------------")
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue
    elif pirates == "4":
        print("-------------------------------------------------------------------------")
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------") 
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------")
        user4 = raw_input("Assign user4 name:")
        print("-------------------------------------------------------------------------")
        while 2 == 2 :
            print("-------------------------------------------------------------------------")
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user4))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue        
    elif pirates == "5":
        print("-------------------------------------------------------------------------")
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------") 
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------") 
        user4 = raw_input("Assign user4 name:")
        print("-------------------------------------------------------------------------")
        user5 = raw_input("Assign user5 name:")
        while 2 == 2 :
            print("-------------------------------------------------------------------------")
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user4))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user5))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue
    elif pirates == "6":
        print("-------------------------------------------------------------------------")
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------") 
        user4 = raw_input("Assign user4 name:")
        print("-------------------------------------------------------------------------")
        user5 = raw_input("Assign user5 name:")
        print("-------------------------------------------------------------------------")
        user6 = raw_input("Assign user6 name:")
        print("-------------------------------------------------------------------------")
        while 2 == 2 :
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user4))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user5))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user6))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue
    elif pirates == "7":
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------")
        user4 = raw_input("Assign user4 name:")
        print("-------------------------------------------------------------------------")
        user5 = raw_input("Assign user5 name:")
        print("-------------------------------------------------------------------------")
        user6 = raw_input("Assign user6 name:")
        print("-------------------------------------------------------------------------")
        user7 = raw_input("Assign user7 name:")
        print("-------------------------------------------------------------------------")
        while 2 == 2 :
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user4))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user5))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user6))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            print("Chance of %s"%(user7))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------")
            continue    
    elif pirates == "8":
        user1 = raw_input("Assign user1 name:")
        print("-------------------------------------------------------------------------")
        user2 = raw_input("Assign user2 name:")
        print("-------------------------------------------------------------------------")
        user3 = raw_input("Assign user3 name:")
        print("-------------------------------------------------------------------------")
        user4 = raw_input("Assign user4 name:")
        print("-------------------------------------------------------------------------")
        user5 = raw_input("Assign user5 name:")
        print("-------------------------------------------------------------------------")
        user6 = raw_input("Assign user6 name:")
        print("-------------------------------------------------------------------------")
        user7 = raw_input("Assign user7 name:")
        print("-------------------------------------------------------------------------")
        user8 = raw_input("Assign user8 name:")
        while 2 == 2 :
            print("-------------------------------------------------------------------------")
            roll = raw_input("Do you want to roll the dice ,click y :")
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user1))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user2))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user3))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user4))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user5))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user6))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user7))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            print("Chance of %s"%(user8))
            dice = random.randint(1,6)
            print(dice)
            print("-------------------------------------------------------------------------") 
            continue
    else :
            print("Error: Invalid number of users")
            print(""" Number of players you entered are invalid
                          Breaking Program.....
                          Restarting..
                  """)
            print("_______________________________________________________")
            continue

    
    
